### ISSUE TITLE
安装后要求输入账号密码

### ISSUE THREAD

**Issue by JarhomChen** [ycmbcd/md-Blog#2]
安装后弹出登录框，要求输入账号和密码，我看wiki中说到重置密码方法
忘记密码或者修改密码，直接删除 /data/blog.lock 文件即可。

但是data文件夹下只有visitor文件，删除后还是无法重置，求大神解惑

**Comment by JarhomChen** [comment]
可以了，站点配置错误

**Comment by ycmbcd** [comment]
好的，祝您使用愉快，有问题随时联系。

**Comment by ycmbcd** [comment]
好的，祝您使用愉快，有问题随时联系。  

--  
春明
已使用 Sparrow (http://www.sparrowmailapp.com/?sig)


在 2020年1月10日 星期五，下午7:48，Jarhom 写道：
