### ISSUE TITLE
生成静态页面后外链图片无法显示

### ISSUE THREAD

**Issue by andyppang** [ycmbcd/md-Blog#3]
显示的是外链图片的地址，是否程序目前还不支持该功能？
好像是对html代码没做处理
![Snipaste_2020-09-26_23-45-44](https://user-images.githubusercontent.com/24608102/94344914-3537c680-0055-11eb-8c0a-ab8880d03523.jpg)

**Comment by andyppang** [comment]
好像是对html代码没做处理

**Comment by ycmbcd** [comment]
由于外链图片可能失效影响文档阅读体验，顾没有开发，抱歉，今后可能会考虑加进来。
